[INFRA/feat] 무중단배포 테스트

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -21,7 +21,7 @@ pipeline {
         stage('Pull from GitLab') {
             steps {
                 git url: 'https://lab.ssafy.com/s09-fintech-finance-sub2/S09P22A607.git',
-                    branch: 'be/develop',
+                    branch: 'feat/70',
                     credentialsId: 'ab6625fd-a8a2-4a73-a301-bd4f0edbb103'
             }
         }
@@ -45,6 +45,8 @@ pipeline {
                         gradle wrapper
                         chmod +x gradlew
                         ./gradlew clean build -x test --stacktrace
+                        pwd
+                        ls
                     '''
                 }
             }
@@ -60,22 +62,69 @@ pipeline {
         //     }
         // }
 
-        stage('Delete existing Docker images and containers') {
+        // stage('Delete existing Docker images and containers') {
+        //     steps {
+        //         sh'''
+        //             if docker container inspect haruman_server >/dev/null 2>&1; then
+        //                 echo "container exists locally"
+        //                 docker stop haruman_server
+        //                 docker rm haruman_server
+        //             else
+        //                 echo "container does not exist locally"
+        //             fi
+        //             if docker image inspect server >/dev/null 2>&1; then
+        //                 echo "Image exists locally"
+        //                 docker rmi server 
+        //             else
+        //                 echo "Image does not exist locally"
+        //             fi
+        //         '''
+        //     }
+        // }
+
+        stage('Blue Health Check') {
             steps {
                 sh'''
-                    if docker container inspect haruman_server >/dev/null 2>&1; then
-                        echo "container exists locally"
-                        docker stop haruman_server
-                        docker rm haruman_server
+                    #!/bin/bash
+
+                    if curl -s "http://3.34.135.50:8081" > /dev/null
+                    then
+                        deployment_target_ip=3.34.135.50:8081
                     else
-                        echo "container does not exist locally"
+                        deployment_target_ip=3.34.135.50:8081
                     fi
-                    if docker image inspect server >/dev/null 2>&1; then
-                        echo "Image exists locally"
-                        docker rmi server 
+
+                    scp -o StrictHostKeyChecking=no ./build/libs/zero-downtime-deployment-practice-0.0.1-SNAPSHOT.jar root@${deployment_target_ip}:/home/ubuntu
+                    ssh root@${deployment_target_ip} "nohup java -jar /home/ubuntu/zero-downtime-deployment-practice-0.0.1-SNAPSHOT.jar > /dev/null &" &
+
+                    for retry_count in \$(seq 10)
+                    do
+                      if curl -s "http://${deployment_target_ip}:8080" > /dev/null
+                      then
+                          echo "Health check success ✅"
+                          break
+                      fi
+
+                      if [ $retry_count -eq 10 ]
+                      then
+                        echo "Health check failed ❌"
+                        exit 1
+                      fi
+
+                      echo "The server is not alive yet. Retry health check in 10 seconds..."
+                      sleep 10
+                    done
+
+                    ssh root@${nginx_ip} "echo 'set \\\$service_url http://${deployment_target_ip}:8080;' > /etc/nginx/conf.d/service-url.inc && service nginx reload"
+                    echo "Switch the reverse proxy direction of nginx to ${deployment_target_ip} 🔄"
+
+                    if [ "${deployment_target_ip}" == "${blue_ip}" ]
+                    then
+                        ssh root@${green_ip} "fuser -s -k 8080/tcp"
                     else
-                        echo "Image does not exist locally"
+                        ssh root@${blue_ip} "fuser -s -k 8080/tcp"
                     fi
+                    echo "Kill the process on the opposite server."
                 '''
             }
         }
